on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  reviewdog-check:
    name: reviewdog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Dependencies
        run: npm ci

      - name: Execute textlint
        run: |
          npx textlint -f checkstyle **/*.tex > textlint.log
          if [ -s textlint.log ]; then
            cat textlint.log | reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
            exit 1
          else
            cat textlint.log | reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
          fi
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
